language: java
sudo: false
dist: trusty
jdk:
# - openjdk6
  - openjdk7
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -q
# See bugs.openjdk.java.net/browse/JDK-8212233 for why jdk11's javadoc is borken
script: "mvn verify -Dgpg.skip=true -Dmaven.javadoc.skip=$(echo $TRAVIS_JDK_VERSION | egrep -q 'openjdk(6|11)' && echo -n true || echo -n false) -B -q"
